version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
      nx:
        patterns:
          - '@nx/*'
          - 'nx'
      github-actions:
        patterns:
          - '*'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - '*'
