export type { AppError } from './lib/error-service';
export { ErrorService } from './lib/error-service';
export { Gamification } from './lib/gamification';
export { LayoutStore } from './lib/layout-store';
export type { ShellLayout, PanelCollapsedState } from './lib/layout-store';
export { renderMarkdown } from './lib/markdown-renderer';
export { ProgressStore } from './lib/progress-store';
export { Seo } from './lib/seo';
export type { SeoConfig } from './lib/seo';
export { ThemeService } from './lib/theme-service';
export type { Theme } from './lib/theme-service';
